services:
  dev:
    # special dev container that contains everything
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-dev
      args:
        ROS_DISTRO: jazzy
    volumes:
      - ./webrtc_bridge:/root/ws/src/webrtc_bridge:rw
      - ./webrtc_sender:/root/ws/webrtc_sender:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - $HOME/.Xauthority:/root/.Xauthority:ro
    devices:
      - /dev/video1:/dev/video0
      - /dev/dri:/dev/dri
    environment:
      - DISPLAY=$DISPLAY
      - XAUTHORITY=/root/.Xauthority
      - QT_X11_NO_MITSHM=1