services:
  webrtc_bridge:
    # Receives ROS 2 WebRTC-data (as server) and publish as ROS-Images
    image: webrtc_bridge
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        ROS_DISTRO: jazzy
    ports:
      - 9999:9999

  viz:
    # ros2 image viewer to visualize
    image: image_viz
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-img-viz
      args:
        ROS_DISTRO: jazzy
    environment:
      - DISPLAY=$DISPLAY
      - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - $HOME/.Xauthority:/root/.Xauthority:ro
    devices:
      - /dev/dri:/dev/dri

  cam:
    # provide the local camera
    image: webrtc_camera
    build:
      context: ./
      dockerfile: ./docker/Dockerfile-cam
      args:
        ROS_DISTRO: jazzy
    devices:
    - /dev/video0:/dev/video0

# TODO: Web-Server for WebCam from Browser