ARG ROS_DISTRO=jazzy
FROM ros:$ROS_DISTRO

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    qtwayland5 \
    ros-$ROS_DISTRO-rqt-image-view \
  && rm -rf /var/lib/apt/lists/*

COPY ./docker/entrypoint_jazzy_only.sh /ros2_ws_entrypoint.sh
RUN chmod a+x /ros2_ws_entrypoint.sh
ENTRYPOINT [ "/ros2_ws_entrypoint.sh" ]

CMD [ "ros2", "run", "rqt_image_view", "rqt_image_view"]