ARG ROS_DISTRO=jazzy
FROM ros:$ROS_DISTRO

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    qtwayland5 \
    mesa-utils \
    python3-colcon-ros \
    python3-pip \
    python3-pkg-resources \
    python3-opencv \
    python3-venv \
    python3-aiortc \
    python3-aiohttp \
    ros-$ROS_DISTRO-cv-bridge \
    ros-$ROS_DISTRO-rqt-image-view \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /run/user/1000

ARG COLCON_WS=/root/ws/

ENV PYTHONWARNINGS="ignore:setup.py install is deprecated::setuptools.command.install"

COPY ./docker/entrypoint.sh /ros2_ws_entrypoint.sh
RUN chmod a+x /ros2_ws_entrypoint.sh
ENTRYPOINT [ "/ros2_ws_entrypoint.sh" ]

RUN mkdir -p ${COLCON_WS}/src

COPY ./webrtc_bridge/requirements.txt /tmp/requirements.txt
# install requirements.txt
RUN pip3 install -r /tmp/requirements.txt --break-system-packages

COPY ./webrtc_bridge ${COLCON_WS}/src/webrtc_bridge

WORKDIR ${COLCON_WS}
RUN . /opt/ros/${ROS_DISTRO}/setup.sh && \
  colcon build --symlink-install

COPY ./webrtc_sender ${COLCON_WS}/webrtc_sender

# Add install/setup.bash to bashrc so the python interpreter inside
# the devContainer can find the ros-installation and autocomplete works.
RUN echo "source ${COLCON_WS}/install/setup.bash" >> /root/.bashrc

CMD ["sleep", "infinity"]