FROM python:3

RUN apt-get update -qq \
  && apt-get install -y \
    python3-aiortc \
    python3-aiohttp \
    python3-pip \
  && rm -rf /var/lib/apt/lists/*

COPY ./webrtc_bridge/requirements.txt /tmp/requirements.txt
# # install requirements.txt
RUN pip3 install -r /tmp/requirements.txt --break-system-packages

COPY ./signaling_server /signaling_server

CMD ["python3", "/signaling_server/server.py"]